<?php

namespace GeneralBundle\Repository;

use GeneralBundle\Abstracts\RepositoryAbstract;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends RepositoryAbstract
{
}
