<?php

namespace GeneralBundle\Repository;

use GeneralBundle\Abstracts\RepositoryAbstract;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends RepositoryAbstract
{

}
