GeneralBundle\Entity\User:
    type: entity
    repositoryClass: GeneralBundle\Repository\UserRepository
    table: account
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 28
            nullable: false
            unique: true
        password:
            type: string
            length: 512
            nullable: false
        email:
            type: string
            length: 128
            nullable: false
            unique: true
        first_name:
            type: string
            length: 28
            nullable: true
        last_name:
            type: string
            length: 28
            nullable: true
        info:
            type: text
            nullable: true
        avatar:
            type: string
            length: 512
            nullable: true
        role:
            type: string
            length: 16
            nullable: false
        rate:
            type: integer
            nullable: false
        date_registration:
            type: datetime
            nullable: false
        date_last_login:
            type: datetime
            nullable: true

    oneToMany:
        tests:
            targetEntity: Test
            mappedBy: author

    manyToMany:
        passed_tests:
            targetEntity: Test
            inversedBy: passed_users
            joinTable:
                name: user_passed_test
                joinColumns:
                    joinColumn:
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    joinColumn:
                        name: test_id
                        referencedColumnName: id
        passed_answers:
            targetEntity: Answer
            inversedBy: passed_users
            joinTable:
                name: user_passed_answer
                joinColumns:
                    joinColumn:
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    joinColumn:
                        name: answer_id
                        referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [ setDateRegistrationValue, setRoleValue, setRateValue, setLoginValue, setPasswordValue ]
        preUpdate: [  ]
        postPersist: [ uploadAvatar ]
        postUpdate: [ uploadAvatar ]